### PR TITLE
Only require typing_extensions on Python 3.7 and older

### PR DESCRIPTION
**Pull request by gitpushdashf**
Corrects a typo in README.rst.

Newer mypy versions output double quotes instead of single quotes.

### CODE REVIEW

**Comment by shabbyrobe** [comment]
Thanks for the PR, this looks good.

Do you happen to know which mypy version introduced the change? We should probably set that ti be the minimum in the version constraint.

**Comment by gitpushdashf** [comment]
Thank you! I'm glad it looks good.

From what I can tell, it happened going from mypy 0.812 to 0.900. 0.902 is out right now.

Do you want me to update dev-requirements.txt accordingly?

**Comment by shabbyrobe** [comment]
Yes please. Maybe we could start with 0.902 and wind it back (or forward) if anybody has trouble?

**Comment by gitpushdashf** [comment]
Ok, that's done.

**Comment by gitpushdashf** [comment]
Thank you!

**Pull request merged**
