### PR TITLE
Call and ServicerContext should each extend RpcContext

### PR DESCRIPTION
**Pull request by MHDante**
Likely a miss due to stub generator mixed with six

### CODE REVIEW

**Comment by MHDante** [comment]
This one is a bit hairy, since Call.cancel is not documented to return anything. however, Future suggests a boolean 

I've left Call.cancel untyped to allow coersion, (I tried finding the actual return type, but quit when it hit the cython impl)

**Comment by shabbyrobe** [comment]
Looks good, thanks for the PR!

Do you anticipate this will break anybody's code if we remove the current type from `cancel()`, or will this be less broken than what is there currently?

**Comment by MHDante** [comment]
Anyone **using a strict mode** linter that has a call to

```
my_var = my_rpc_context.cancel()
```

...will have their linter error that `my_var` has type `Any` instead of `None`.

the question would then become why they stored the `None`? furthermore, `my_var` may have contained a bool, which could have been true.

In short: should be fine.

**Comment by MHDante** [comment]
@shabbyrobe LGTM?

**Comment by shabbyrobe** [comment]
Yep, LGTM! Merged, thanks for the bump and the PR.

**Pull request merged**
